language: python

python:
  - 3.5.2
  - 3.6-dev

install:
  - sudo apt-get install enchant
  - pip install -r requirements-dev.txt

script:
  - python setup.py test --coverage -q
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then python setup.py test --coveralls; fi
  - python setup.py bench


notifications:
  email: false
